name: novious
version: 1
accesskey: 2o4yky5klm

#cron:
#    - description: cron test
#      url: mycron/test.php
#      schedule: 00 19 2 10 *
#    - description: another cron test
#      url: mycron/run.php
#      schedule: */30 * * * *

handle:
    -rewrite: if ( path ~ "^article-([0-9]+)-([0-9]+)\.html$") goto "portal.php?mod=view&aid=$1&page=$2&%{QUERY_STRING}"
